import re

def findXMAS(input_str):
    pattern = r'(?=XMAS|SAMX)'
    return re.findall(pattern, input_str)

def findXMAS_matrix(matrix):
    count = 0
    for i in range(len(matrix)): # searching in both forward and backward directions
        horizontal = findXMAS(matrix[i])
        count += len(horizontal)
    return count

def convert_verticalmatrix(matrix, n, m):
    verticalmatrix = []

    for j in range(m):
        verticalstring = ''
        for i in range(n):
            verticalstring += matrix[i][j]
        verticalmatrix.append(verticalstring)

    # printmatrix(verticalmatrix)
    # print(verticalmatrix)
    return verticalmatrix

def convert_diagonalmatrix(matrix, n, m):
    diagonalmatrix = []
    for i in range(1, n+m):
        diag = ''
        startcol = max(0, i-n)
        diag_count = min(i, m-startcol, n)        
        for j in range(diag_count):
            row = min(n, i) - j - 1
            col = startcol + j
            diag += matrix[row][col]
        diagonalmatrix.append(diag)
    # print(diagonalmatrix)
    return diagonalmatrix

def convert_revdiagonalmatrix(matrix, n, m):
    revdiagonalmatrix = []
    # diagonals from top row R -> L (top half)
    for col in range(m-1, -1, -1):
        diag = ''
        i = 0
        j = col
        while i < n and j < m:
            diag += matrix[i][j]
            i+=1
            j+=1
        revdiagonalmatrix.append(diag)
    
    # diagonals starting from second row (bottom half)
    for row in range(1, n):
        diag = ''
        i = row
        j = 0
        while i < n and j < m:
            diag +=matrix[i][j]
            i += 1
            j += 1
        revdiagonalmatrix.append(diag)
    # print(revdiagonalmatrix)
    return revdiagonalmatrix

# for testing purposes only
def printmatrix(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            print(matrix[i][j], end=" ")
        print(" ")
    print(" ")

def question4(matrix):
    """Takes input as a list of strings by row. Outputs number of searches"""
    n = len(matrix)    # number of rows in matrix
    m = len(matrix[0]) # number of columns in matrix    
    count = 0

    # horizontal search
    count += findXMAS_matrix(matrix)

    # vertical search (start at column 0)
    verticalmatrix = convert_verticalmatrix(matrix, n, m)
    count += findXMAS_matrix(verticalmatrix)

    # diagonal search from top left to bottom right
    diagonalmatrix = convert_diagonalmatrix(matrix, n, m)
    count += findXMAS_matrix(diagonalmatrix)

    # diagonal search from top right to bottom left
    revdiagonalmatrix = convert_revdiagonalmatrix(matrix, n, m)
    count +=findXMAS_matrix(revdiagonalmatrix)

    return count

# test = ['MMMSXXMASM', 'MSAMXMSMSA','AMXSXMAAMM','MSAMASMSMX','XMASAMXAMM','XXAMMXXAMA','SMSMSASXSS','SAXAMASAAA','MAMMMXMMMM','MXMXAXMASX']
# printmatrix(test)
# print(question4(test))

test2 = ['XMMXMASAMSAAAXSXMASAMSMXSAMXMMMMXMSSSSXMAMSAMXMSXMMASAMXMMMMAXMXMSMSMXSXMXSMXXSAXXMSXSMXXXSASXSMMSSSMMXMAMSMSSSMXMAXXXXSSXXXXMXSXAXMASMMSASM',
        'SAMXXAMXMAMAMMMAXSAXMAAMSMSXSAXMAMAAASAMXMSASAMMAMXAAASAMAASAMXXSAAAMMSAMASMMAMASMMSAMXSXMSASAAXAXMAMMAMAMAAAAAAAXSMMMMMMMMMXMAMXMAXXMAXSAMX', 
        'MAAAMSSMSASASASXMXMXSMSMXAAAXAXSAMMSMXXMSXSMMAMSAMMMMAMASXMMXMMMSMSASASAMASASAMAMAAMAMASXAMAMXMMMXSAMSMSASMMMSMMMXAAXAAAAAAXAMASAMAASMSMMXMX', 
        'SMMXXAAAMAXASAMSAXXXAMXMMMMMMAMSASAXMXSSMMXASAMMXMASMMMMMMAMXMAMXXXMMMXAMMSAMMMSMMMMXMASMSMAMAXAXAMXMAAXXMXMAXAAMSSMMSSSSSMSMSASMMSXMAMMXSSX', 
        'XXMMSMMMMSMMMXMMMMXAMMAMXMASXSXSAMXSMAMAAXMMMASMASMSAAXSASAMAXSSSMXSASMSMXMMMMAMAAAAXMMXAXMAXXXSMASXSSSXSXXMAMMMMAMXAAMXAXAAXMASXAMAMMMSAAXX', 
        'MXMAAXXXAAAXXMXSXMASXSASMMSMAAAMMMXAMXSSSMMAMXMMASASXMMSASMXSSMAAAASXSAMXMAMXMAMXMMAXSAMSMSSXSAXMAMMAAAAXXSMSSSMMMXMSSSMSMSMMSASMMMAMXAMMMMS', 
        'MXMXSSXMSSSMSMMMASAMASXMAXAMXMAMAMXXMXMAMMSAXSAMXSAMAMXMAMAAMAMSMMMMMMAMMXAMAMMSMSMXMAXSXAXAAMAMXSMMMMMXMASAAAAXXSAAMAXAAXMXMMAMASMSMMXXXAAM', 
        'MASAMXXXAAAAXAASXMXSASAMSSMSMSMMASXMMAMAMMMAMSASAMXMXMAMAMMMSAMXXAAAAXAMMSSMSSXAASAMXXSAMXMMMMASXMAXMAXAXAMMMSMMASXSMMMSMSXAAXXMSMMAAMXSSMSS', 
        'MAMASASMMSMMMSMSMSXMAMXXAAXAAXMSAXAXSASASAMMMMAMXXAXSXXSXSMASAMXSSSSMSASAXAAXMXMSMXXXMXXAXMSXMMSASXMSSSMMMSMMXAMXMMMASAMXSXMSMMXXXSSMMAMAMAM', 
        'MASXMAXSAAMSXMAMAMAMAMXMMSSMSMMMMXMMSAXXSXSASMMMSMMASAASAXMASAMXAXAAMSAMXSMMSAAXAXMMMMAMMMXSAMSMMMAXAMMXMAMAAMXSAMASAMAXAMMXAXMAMMXAXMASMMAS', 
        'MXXAMXMASMMSASAXSXMMASAAMAMXAAMAAAMXMSMMXASASAAAXAMASXMMAMMAMAMAMMMMMMXMASXAMXMSMMXAAXASXAAMAMAAXSXMMSMAMASMMSASASXSSSSMSSSSMMSASXSXMAXMXSAX', 
        'SSSSMSAMXMASAMMXXAXMASMXMASMSSSSSMSAAMXMMXMAMXMMMXMASAMXSMMAXSMMSASAXMSSXMMSSSMAXASXXSASMMMSAMMSMMAXMAXASMSXSMMXAMMSAXXAAAAXAASAMASMMXSXAMAS', 
        'XAAXASMXAMAMXMMAXAMXXMXSMXXXAMXMAAXMMMAMXMMSMSSSSSMXSAMAMXMXXMAAXASASMAMAMSXMASMMMSAAMMMAAASXSMXXXAXXMSXSASMSASMXMSMMMMMMSMMMMXAMAMAXASMMMXA', 
        'MMMMMXSSSSSMXSMXSSXXXAAXXSSMSMAMSMXSASMSAMXAAXAAAXMASAMASMSMAMMMMMMAMMAXAMXAXAMXAMMMMXMSSMMSAAAMMMMMMXMASAXAXAMXXMXAXXSAAMAMXMSAMXSSMAMAXXMA', 
        'ASXMMAXXAAXMMAMAXMASMMMSMMAAXXMMAXMSAXASAXSMSSMMMMMXMAMXXAAAAXAXAAMXMXMSMSSSMMMSAMXMSAMMAMAMAMAMXAAAMAMMMMMSMMMSSMSMMMMMMSAMAMMSMAMXAMSMMSAS', 
        'XAAAMMSMMMMXMAMXXSASAAAXASMMMAMSASMMSMMMSMAXAXMSXXMAXXMSMSMSMXMSXMSMMXMAMXAMXAXXSXMASXMSAMXSASASXMSXXAXAAAAXAXAXXAAAAAAAXSAMXSAAMASMSAAMAMXA', 
        'SSSMMMAAAXXAXSXSAMXSXMMSMMMASAMSSMAAAMAAASXMAXMXMAMMXMAAAAXXAMXMXASAAAMXSMMMSXSAMSSXMXMSAMXSASASAMAMSMMSSMSSXMASMMMSXSMSXSXSXMMMXASAXMXMASMM', 
        'AAAMAMSSMSSMSAXMMMMMASXXMMSAMMXXAXXSMSMXXMMXSXMAXXAASMSMSMSMMMAAAXSAMXSMMASXAAMAMAMAMMMXMSMSXMXSXMAXXSAXAAAAAXMAMAAXAXXMASAXAMXSMASAMXMXAMAX', 
        'MMMXAXXMAXMXAMMSAAASXXMMXAMMSSXSAMMMMAMXXSMAXASMSSMMSAXAAAAAAMMXMMMMAXAAMAMXMXSAMASXMASAMXAMXSAMXMSSXMSSMMMSSMSAMMSMMMMMMMSMAMAXMAMAMXAMSMMS', 
        'XMXSSXSMSMSXXXAXXXXXMMMSMMSMAAXAXXAASXSAASMXSAMAAXAXMMMSMXSSMMMAXXAMXMSMMASXXASASASXSXSMMMSMAMASAAAMAAAMXSXMXXMAMXAMXAAXSAAXAMXSMMXMMXMAAAXA', 
        'XAAXMASAMAAMSMSSXSSMAMAAASMMMSSMMSSMSAMMXMAMMAMMMMSMXSAXAMMAMASXSSSSSMAXXAMXSASXMAMMMAMAASAMXSASMMASMMMSAMAAXSMSMSSSSMSAMSSSMSAMXAASASXSSSMM', 
        'SMMSMAMAMMMSAAAAAAMSMMMMMMXXSAXAAXMMSASMSMSMSSMSMXXAMXSMXMSAMMAAAAXAAMAXSAXAXXXXMXMAMAMMMSASMMAXXMAXXSXMASMMMXAXMAXXAAMAAAMAMXXSMSMSAXMAMXXX', 
        'XSAXMASMMMMSMSMMMMXSMMXSAMXSMMSMMMMXSAMAAAXAAMAXSAMAMSMSXAMXMAMMMMMXMMAXSXMAXXMXMASMSMSMXSAMAMMMASASMXASAMXXAMSMMMSSSXSMMXSXMASMMMAMAMMXSAMX', 
        'SMMMXXXMAMXMXXAXXXMXAAAAXAMXAXSXMMSAMAMSMSMMAMMMMMSAMXASMMMSMMXXAXMXAMXXMXAMSMSASMMAAAMAMXMSMMAMMAAAAMXMSSSMMXMAMXAAXMXMMMXXMXMAAMXMMMXAMASA', 
        'AMAAXSSSSSXSAMMMMXAXMMSSMMMSMMSAMAMXSXMMMXXSAAAXAXMASMMMASXSAXMMMSSMSMSASMSMSAAASXSSMSMSMMXSXSASAMMMSMMAXMAMXAMAMMMSMSASASMSSSSSMSSSXSXMSAMM', 
        'MMMXSAAAAXAMMSSSMXSAAAAAMXAAMASAMMXMMXXXAMASMSASMSXAMAXSXMASXXAASXMAAASAXAMXMXMMMAAAXXMAAAAMMMASMMMAMAMMMSXSXXXASMMAAXASXSAMXAAXSAXMASAMMXMX', 
        'XMAMMMMMMMMSAMAAAAASMMSMAMSSSMSMMSSMMASAAMAMMMMAASMMXSMMAMMMAMSMSAMMMMMXMSMAMXMMXASMMASMSMXSXMAMXSMAMMMSAMXMASXMMAMMSMMXXMMMMMMMMXAMXMASASXM', 
        'MASXAXSXXMASMMMMMMXMMAXXSXAAAAMXAAMAMASXMMXSASXMMXAMAXASMMSMAMAAXXMASMMSAASAMAMMMMMXSXMXXMMSMMMSASMMMSAMAXAMXMASMMMAXAXMASAMAAAXXMXMXMSXXMAM', 
        'SAMMXSAMXMMSXMSSMXSSXXMAMMSSXMXMMMSAMXSAMXXMASXMMSSMMMAMXAAMMSMSMMSASAXMSXSMSMSAAASASAMXMMXXAAAMMSASMMMSASXMSSMMSAMASMSAMMASXSXSMASMMMMSMSXM', 
        'MASXMXMASMXXMMAAMAAXMXMASAXAXSAMSASASAMAXMMMXMXXAAAAXMXMMSSMMAAAMAMXMXAMAMSAAASAXXXMMAMAMSMSMMMSAMMMAAMXMAXXMAMAMXSAAAMMMSAMXMASAMXAAAAXMAAX', 
        'MAMXAAXXAMXMMMSSMMMSAMSMMMMSMMASMXXMMAMAMSAMXMMMMSSMMSMAXAXAXMXMSMMSMMSAXAMMMXMASXSSSMMAMAAXAMXMAMASMMMAXASMSAMXXAAMMXMAXMAMMMAMAXAMSMSSXSSM', 
        'MASXSXSAASXAAAXAXXAXMASXMAXAXMSMMAMSSXMSXSASMSAAXAAAAXMXMMSSMAAXXXAAXAXMMMMXMSMMMAAMASXSSMSMASMMMSASXXSAMXSASXMAMXSSXMMMXMAMAMSSMMXXAAXMAMXX', 
        'SXMAXAMMMMMSMSSSMMMSXASXSXSSMMMAMXMAAAMXASXMASXSSSSMMSXSAAAAMMMSAMSSMSSXSSMAMXASMMMMAMXAAAMXXMAAAMXMAASAMMMAMAMAXSAMMSAAMMSSMMAAMXSMMXMMXMAX', 
        'XAAAMAMAMAXAMXMMAMXMMXSXMAMAASMSMAMXSMMMAMAMXMAXMMXAXAASMMSSSMMXXXXXAXXAAXSAMXXMASXMMSMSMMMAMSMMMSAMXMSAMXMASXMAXMAMAMMMSAMAMMXSMASXXAAMXMSS', 
        'XXMSMMSXSXSXMAXSAMAXMASMSAMXMMAAAMMAMAXMMMXMMMSMMXSMMMMMXMAAAAMMMSMMSMMMMMSMXXSXXMMMAAAXMMMSMAAAXSXSAAXXMXMASASXXSMMXSAAMASAMMAMMMXASXMMASXA', 
        'MSXMAAMMSAMMSXXMMSMMSAMXSASXSMSMSXMAXMXASXXXAAAAXXMMASXSAMMSSMMAAAASAMXMXXMASXXMAXAMMMMXXAAAMSXMXSASMSMSMSMXSXMXMAAASMMMSXMXSMAMASMAMAASXMMM', 
        'AXAXMMMAMAMASMMXAAAAMASASXMASAMAMMSSSMSAMXMSMSMSMSAAXXASASXAXMXMSSSMMSASMSMAMXAXAXSXMXSMSMSSMMSXXMAMAAAAAAMMSXMXAMMMXXAAXASXXMMXAMMMMXMMAMSX', 
        'XMMMSMMMSAMASAMSSMSMSMMASAMXMMMAMMAAAXSAMXXSAMXMASMMSMAMAMMMMXAMXMXAASASASMMSSMMSXXAXAAXXXAXAAAMAMXMXMSMSMMAXAMASXSAXSMSMAMXXSSMSMSASMAMAMAA', 
        'MAAASAMXSXMXMAXMAMXAAXXAXMMMMMSMSMMSMMMASASMAMAMAMMAMMAMMMMXAXASMSMMMSAMXMAMAAAAMASAMSSMMMSSMMSAMXXSXMXAAAMSSXMAMMSAMXAAMAMXMXAAAAXAXXAMMMMS', 
        'ASMMXAMAXXAXXSXXXMMMMSMSSSXXAAAAAXAMMSSXMXXMAMMMMMMMSSSSXAMXSAAAAAAAAXAMXSXMSSMMSAMXMAAASAAXXAAMXMMMASMSMMXMAMSXSAMMMSMMXAMXXAMMMSMSMSSXSAAM', 
        'XXSMXSMMSSMXMAMSMSMSAXAXAMXSMSXSMMXSAAXXMASMXSAAASAMAXAAMSMAMMMMSSMMXSMMXMAXAAMAMMMXMSSMMMMSMMSXSXASXMAXXSAMXMMAMMMAXAASXSSMSXSAXAAAAXAASMMS', 
        'SXMXAXAMXMASMXMAAAAMMMSMMMAMMAAMXMAMMMSMSAXMASMSMSASMMMMMXMMSXMXMAASAMAAMXMMMSMAMASAMXAXXXXSAMXAXSMSMMXMXXMXMSMXMASMSSXMAAAAAAXXSMSMSMMMMAXM', 
        'SAMMMMAMMMAMXMSMMMXMASXAAMMSMMSMAMMSMXAAMXSXXXAXAXMMXSAXXXSXMASASMMMASAMXASXMAMXSASASMSMMMMSAMMXMMXMXMAXSSSSMAAASXSAMXMXMSMMMSMAMAAXAXXASXMS', 
        'SAMASXMMXMASXMAMMXSMMMMSMSAAAMXMSMMAXSMXMASMMMSMSSSMAXMMMXMASASMSAASAMXSSXSAMASMMASAMXAAMSASAMMMSMAXXSXSXAAASMSMSAMMMASAAAMXAAMAMSMSSXSXSAAA', 
        'SAMAMAXSAMMSMSAXXAMAXAAXXSMSSMAXMASMMMSAMXSAAXAAXAAMXMXAMAMXMXSXSXMMXSAXXMSMMASAMMMXMXSXMAXXAXXAASMMMMSAMMSMMMXXMMMXSASMSMSMSMSXMMAXMASMXMSM', 
        'SXMMMSMSASASXSMSMASXMMMSASAMXMAMSAMXAAAXAASMMSMSMSMMXMSSMXMAMXMMMXXXXMXSSMMAMAMXMAMMSAMXXMASMMMMMASAXXAXMMAXAMXXMAMAMMSXXAXXMXMMMMXMMMMAMXAX', 
        'MMMXAMMMXMASAMAXMAMAMSAMXMXMXAMMMSSXMXMXMAXXXXAAXMASAAAAMSSMSXXAXSMMXSAMXASXMMSASMSMMASMSXMAAASXSASXSMMSSXMSSSSSSSSXSASMMMMMMXSAMMMMAXASAXMS', 
        'MXSMMSASAMXMAMSMMSSMMMXXMXXMAXAXAXMASAMXSAMSXSSMXSASMMMSMAAXAXSMMSAMXSAMSMMSAMXXMASASAMXAAXXSMMAMASMMAXAXAXAXAAAAAAASAMXAXAAXMASAAASASMMSSXM', 
        'XAXAMXXAMXAMAMAAXAAASXSMSAAXMASMXMSAMASXMAXSAMXSAMXXXMAXMXSMMAXMAMAMXXAXXAAMMMXAMAMXMASXMMMAMAMSMAMMSAMXSSMMSMMMMMMMMAAMMMSXMXMASMMSAMAAAMAA', 
        'MMSSMXXXXSXSASXSMMSMSAMASMSMMMMAXMASXXMXMMAMXMAMXSXSAMXXSAMAXMSMAMSMSSSMSMMSMMXSMXMXXMXMAASXMAMXMSSMSASXMMAXMAMXXSAMSSMXSAXASMXMAXAMXMSMSXSM', 
        'MAAAXMMMMMMMASAXAXXXMAMMMXAAASMSMSAMXAMMSAMAMMMSAMXAMMXXMASXAASMMXMAMXMAXMASAAAXMMMSSMASXMSAMSMMXMAMSAMXMSSMSMSMXMAXMAMXMASAMAASMSXMSMMAXAAS', 
        'MSSSMSAAAAASMMXMASXXSAMXXMMSMXAAAMASXSMAXAXXMAMXAASXSMSMSMMMMXMAMAMAMSMMMMMXMMXMASAAAMAMAAMMAMXMASAMMAMMXAXAAAAMASXMSAMSMAMASMXAAXMXAAMAMMMM', 
        'MXAAASXSXMMMAMXMAMXAXXSAMXMAXMSMSMMMXAMMSXMXMSSSSMMAAASASMAXMAXAMASXMXMASMSXSAXMXMASMSMSMXMMAXASXSSSXSAMXAMSMSMMAMXASXMASXSAMXMMMMMSSSMSSXMS', 
        'SMSMMMXMXSSSSMAMXSSMSASAMXMAXXAMXAXXSXMASMMAXXAAXAMSMMMAMMAMSXSASASMMASMSAAAAAMSSSXMAAAAXSXMMSMMMXAXAMMAMXMXAAXMMSMMMSXMXMMMSXMAAAAXAXAAXAAX', 
        'XAAAAXMMAAAAXMXSAAAAMAMXMMMSMMSXMAMMMAMXSASMSMSMSAMXAXMMSAXXAAAXMMSXXAXAMXMMMSMAAAAMSMMMMMXSAAAAAMMMXMASXSSMSMXMMAAAAMXXMXAXMASASXSMAMMMSMMS', 
        'MSMSXMAMMMMMMMASMSMXMAMSXMAXASAXSASXSASMXMAAAAAMSMMXXXXAMXXMMSMMMAMXMSSMSMSXXXMMXMXMXXXAXXAMMSMMSAXAMXXMAMXAXXASMMSMASMMAMMSSMMXXAMMXMAMXAAS', 
        'AXAXMMXXXXAMAMASAMXXMAXSAMXMXMAXSAAAMAMAXSMXXSSXSAXSMMMSSMMMAAMSXMXAAAAAMASAMXSASMMSMSSSSMASXMMMMMXSSSMMAMSMMXAXAMAMXAAXSAAMAMMXMMMMSAMSMMMS', 
        'SMAMAASMMSMSAMAXMSMMSMMSAMSSSMMMMMMSMSMMXXXXMAXASMMXAAAXAAMMXSAMAXSMMSMMMMMAXAMXAMXAAAXAXMASAMXASAXXAAAXXXAMMXSSXMAMMXSMMMMSAMXAMSAMXAXMAMXX', 
        'AMXMXMAAAAASMMMXSAXMAMAMAMXAAAASXMXXAXAXSAMSMAMMMXSSSMSSSSMXAMASXMXAAMMMSSSXMXSSSSSMSMMMMXAMAMSASMMMSMMMSSMSSMAAAMXMSMMAXXAMASXMMSXMMAMSSMSA', 
        'MSMMASMMMMXMAAXXSAXSAXAMMMMMMMMSAMXMAMMMXAMXMAMXMAXMXAMXAAMMXSAMMMMMMMAAXMXASXXAAAMXAAMXAXXSSMMXMAMAAXAAXAXAXMASMMMAAAMXMMMSMMASAMMSMSMAAAXS', 
        'XAASASXSASAXSMSMMSMSSSMXMASXSAXSMMMSAAAMSSMXMASXMSSMMSMMSMMSMMASAAMSMSMMSMSAMXMMMMMSSSMXMAAXXXXMSAMSSSMSSMMMSSXXMXASMXMAXAXAXMAMASAAAAASMMMM', 
        'XXXMXXXSASXXAXXAAMMSASAASAMASAXXSAASXXAXAMAMXAMAXAAMAXAAXXMAASAXXXMAAAASAXAASXSAAAXMXMMAMSMMMSMAMXMMAXXAAXXAAXMAMXMMXAMSXMSAXSASMMXMSMXXSAAM', 
        'XSAMMSMMMMXAMXMMMXMMAMMMMASXMMMMMMMSMMSMASXSASMSMSSMSSMMMASMMXASXSSMSMMMXSMXMAMASXSMSSMMMAAAAMMMMXMMXMASMMMMSXSAMXSSSMSAAMMMMSASMSAMXXXASMMS', 
        'XAAAASXMASXXXAXAMASMSMSXSAMXSXMXAMASMAMMMMXSAMAXAAAMXMMAMAMXMXMAXXAAAMASAMXAMXMAMMXXAMASXXSMSSXMASXMAMXMMMSXMXSASXSAAXXMXMASAMAMASMSMSMMMSMA', 
        'XSMMASASXMXXSSSMSMSAMAAXMAMAXAMSXSAMMASAMXAMAMXMMMSSSMSSSMSXAXXXXSMMMSASASMMSAMASXMMASAMXMAAAMAXXAMSSMXMASMAMMSAMXMMMXASXSXMXSXMAMXMAAMAAAXM', 
        'MXAXAXXMAMMMAAXAAXMAMMMXXSMMSSMAXMASMASAMMXXAMASXXAAAAAAAAAMMSMMXMASXMXSAMMMMASXSMMAXMAXSAMMASMMMMAXMXAMMMMAMAMMMXXAXMXMAMMSAMMMXSSMSMSMSSSX', 
        'AMSMSSSMXSAAMMMSMSSXMASAAXSMAXMASMMXMMSXMASMASASXMMSMMMSMMMXAAAXXSASAMAMMMAAMAMXXMASXAMASMXXXAMXAMMMMSMSSXSASMASXXMAXAAMAMAMASXXMXAAAAMAMXAX', 
        'SSXAMAXXASMSXXXAMAAASASMSMAMXMAMXAAXMAXAMAXSAMMSAMAXMAMXXXXMSMSMAMAXMMASASMSSSMMMMMXAASAMXMXMSSSSXSAMXMAXXMAXXAASASXSSXSAMXSMMMSAMMSMMMSMMSA', 
        'XAMXMSMMASXMMMXAMMSMMASXMMAMMMSMSMMSMMSAMXMMXSXSMMSSMMXMXMAXMAMMSMSMASMSASMMAXMAAAXXSXMASASXAAMXAASXMAMXMMXSXSSMMXAAAAAAAXAMXAXASXXAAAXXAAAM', 
        'MMXMAMAMXXMMAMMMMXXXMXMXMSMSAAAAMAAXAAXAXXMSMMAMXMXAXMASAMMXMXXAAAASAMXMMMAMAMXMMXXXMXXMXAMMMMMMMMMASXMSAMAMMMAXMMMMMMSMMMSMSMSMXMMSXMSMMMMX', 
        'AXMAMXXMMSMXXMMSAMXMSASAXMASMSXSSMMSMAMMMSXAXMAMSSMMMSXSAXMAXMMSMSMMMSAMASXMASXSSSMAASXMMSMMSSSXMXSXMAASAMXSASMMXAXAAXMAMMAAAAAXAAMAMSMMASXM', 
        'SMSSXSASAXMASMXMASMXSASXSMAMXMXAAXXMASXAAXMMSXSXSAMSMMASXMSXXAMAXAXAASASMSXMXAXAAMXXAMXMAAAMAXMAXAXAMXMSXMXSXSXMSMSMSMSAMXMSMSSSMMMAMAAMASAS', 
        'XAAAASAMSSMASMAXSMMAMXMAMMMXASMMMSSMAXSMXSAXMAMXMMMAAMAMAMAASMMMSMSMMSXMAMXSMMMMMMSSSSMMMSXMMSSMMSSXMMXMMSXSAXMAXAAMAASMSXAMAAMAXSSSSSSMASXM', 
        'MMMSMMAMAXMAXMAMXAMXMASAMSSMMSAXAXAMAMAMASMSMAMASASXSMASAMMMMMAMXXXXASAMXMAXAXMASAMAAAXSXXXAXAAAAXAAXSASMAAMSMMAMXMSSXMAMMMMMMXAMXAMAAXMMMAM', 
        'XMXMXSXMXSXSSMSMMAMXSASAXAASASMMSSXMSSXMAMMAMAMXXAXAAMASMMXAMSXMMMSMMMXSXMASMMSASAMMMMMXAXSMMXSMMSSMMSASAMMMMXMMSAAXXASXMAAAXAMSSMMMXMASMSSM', 
        'XAAXAMASMMXXAMXMMMMXMMSXMXSMXMMAXAASXSAMSXSASXSSMSMSMMXSMMSAMAMXAAAAASMMASXSXAMXSXMASAXMMMXMAXXMMXAXXMAMMXXAXXXAXMSMSMMASMSSMMSAAAXSAXXAXAMX', 
        'MMSSMSXMASXMMMSXASMSMAMMSMMMAMXSMSMMASMMMAMXSAMXAMAMXSXXAASMMAMSMMSSMXAXAMMMMMSMMASXMXXAASXMXSMASMMMXMXMAXSAMSAMXXAASXSMMXAMMMMXMMMMMSMMMMSS', 
        'XXAAXXASMMSAAAXXASAAMMSAMASMMXMXMXAMMMMAMXMASASMMMSMAMAMMMSMMAMXAAMAMSMMAXASAXAXMMMXSMSSMSAAASMMMAXSMXSAXXMAMAAXAMMXMXMAMXMASAASXSXSAAAAXMAX', 
        'MMSSMXMMAASMMMSAMMMMMXMXSAMXSAMASMMXSXMASAMXMMMAAAAMMSSMSXXASMSMMMSAMAMMXSASXSMMSAMMAAXMAXMMMMAXMMMXAAMAMXMAMMMMMMMXMXSSMXXASMSMMSAMSSSMSMAS', 
        'XAMAXSMMMMSMSAMAMSSXAXSAMASAXASAMASAMAXAXASXAASXMSSSXAAASMMAMAAXSMSAMXSAAMMMMXAAMASAMMSMSMXMSSMMSAAMMMXAAMSSSXSXSASMSAAAMXMASXAMAMAMAMAMMMMS', 
        'MSSMMAAAMSXXMAMMMASMMMAAXAMMMMMMSXMASAMSSMMXSXSAAAAXMMMMMASMMSMMMMMAMAMMXMXAMMMMSAMMXMSAMXMAAAXASXXXMSXMSMAMAAXAMAXAMMXMMMMXMASMSSXMASAMXMSX', 
        'XMAMMXMMSAMMSSMMMASMAASMMSMSMSAXMMSAMXSAAAAMMMMMMMSMMXSXSMMAAMXMAASAMXMXAMMMSAAXMXMMMAMXMMSMXXMASMSAMXASXMMSMSMSMXMSMXAXAAMAMXXAMXMXASMSAMXM', 
        'SAMASAASMMAAAXAAMMSXSXMMXXAAAMMMSMXMXMAXSMMSAAXSAMXAXXXASASMMSASXXSMSXMMASAASMSSMSSSMXAXMAMMSMMAXMASMSMMAXMAMAAMMXXXASMSSXSASMMMMAMMMSASXSAA', 
        'MAMASXSMMXMAXSSMSAMAMMAMAMSMMXAAAXMMMSAXXXAMXMXSASXSMAMXSMMMAMMSMAXXMAMSASMXMAAAAAAAXMASMMXAAAMAXXAMXAMSMMSXSMSMASXMAMAAAAMASXAMMSSSMMAMAMXS', 
        'XAMMXMXAXMAMMAMAXMMAMMAMAMXMSXMMXMAAAMXSMMMSSMMSAMAAMXSXMAMMAMASXMSMSAMMXMMXXXSMMMSMMMAXXMMSSSMSXMMSXXXAMXSAXMMMAMMAXMMMXMMAMMSMAAMAXMAMAMMX', 
        'SMSSMMSAMXAXMAMASXSAXSASMSAMMXSXMASMSSMMAAAAMAAMAMSMMAXAAAMSMSAMAXAAMASXAMSMMMMXAMAMAMXSXMAMAAAAMSXSAXMAXAMXMXMMXMAXMXXMSAMMMAXMMSSMMSMSMXAX', 
        'AXAAAXXMMMSMSXMXAAXAMXMSASAMXAMSSMXAAMAXXMSMSMMMXMAXMMSMMXMAAMXMASMSMXMXXSAMXAXXMXAMXSSMMMSSSMXMAMASASMXMASAMAMXMMSMSXAXAMXSMMSXXMAMMAMAAASX', 
        'MMSSMMSASAMXSAMXMSMMMAXMAMAXXXXAMXMMMSMMXMMXMXMSMSMSAAMAAXMMMXMAXXAXMAMXXMXSMSXSSSSMXSAAAAMXAXSXSMAMAMAASAMMSAXXXAAAMXSAMXASASXXMXSMSASMSMMA', 
        'XAXAAASXMASXMAMSAAAXSSSMSMASMMMSSMXXMAXAAMSASASAAAAMMMSMSSXXSAMXSMXMSSSMSXAMAXAAAAAMMSSMMSSSMMMMXMASMMSMMAXXAAMSMMMSXAXAXMSSXMMMMAMASASAMXXX', 
        'MSSMMMXAXAMASAAXSMSMMAAAXMASAAXAAAXAXAAXAXAAMMSMSMSMAXAAMXAXSASXSAAAXXAAXMMMAMMMMMMAMXXMAMXXAAMXSMXXXMXSXMASMSMAAAAMMMSSXMAMMAASMAMAMSMXMASM', 
        'MXXXAXSSMASXMMSMXMAMMSMMMMASMMMSSMAMMSMMSMMSMXXMXAXXAXMXMMAMMAMMSXSSSXMMMMXMASMXMXXXMAMSSMSMSMSXMXMASMAMXXXAAXMXMMMSAXXMMMMSMSASMSMSMAMSSXMA', 
        'SMMMMMAMMMMAXAXMASAMXXXMAMAXAMAXAMAXAXXAXAAMXXSXMSMMAMSAAXMMMAMMMAMMMAASAMXMXXXAMXMXMXMAMXXAAAMMSAMSMMXSAMSMMMSMMAAXXMAMXMMAAXASAMAASMSAMASM', 
        'MAAXMAXAAAMSMSXSASASMMMMSMSMSMXSAXXMMSMSSMMSMSMAAMAMAAXXXMSXSXSAMXMAXSMSXSMSXSSXMAMASAMMSMMSMSMASASMXMXMAMAAAAAAMMSSMMAMAMMMSMMMAMSMSXMASAMX', 
        'SSMSSSMSSXXAAMASASAMAAAXMAMAXXMSAMSAMSMMXXXAMAXXMSXMMSSSMAAAASAMXAMSMXASAXAAAMMASASXSAXXAAXXSXMXSMMAASMSMSMMMSSSMMAAXSASASXXAAXSMMMXMXSAMASX', 
        'AMAAAAAMAMSMSMAMAMXMMMSSMAMAMAAMAMSAXSASMMSXSMSMMXAXXAAAMXMMMSSXXMAXAMAMXMSMMASXSMSAMAMSMSSSMMSASAMSMXAAMMMMAXMAAMMSMSASASXSASXXMAMXMXMASXMX', 
        'MMMMSMMMAMAAXMXMASASASXAMXSASMMXMMSAMXAMAMMAAAAXMAMMMMMMMASXAXMMMMAMAMXMMXXXSAMXSAMXMAMSAMXAASMMSAMMAMSMMAAMSMSSMMXAAMAMAMASMMMXMAXMSAMXMAMX', 
        'XAAMXXMSXMMSMSXSXSASXAXMMMSAXAAXSASMSMXMXAMSMSMXSAMAXXXSSXSMXXMMSMASAMXSAMMMMASAMAMXMSMXASXMMMAXSXMSMXAAASXSAAXAXMSMXMXSAMXMAXAMSMSASMSMMSXM', 
        'SSMSAMMXSAAMAMAXXMXMMMSMSMMMMMXXMASAMMMMSMMAAAMASASXSMXMAXSMMSMAAXAXAMAXMASASXMXSAMMMMMSAMMSXSAMXXMAMSXSMMXSMMMMAXAAXSAMASXSSMMXAAAXSAMXAAAX', 
        'AMAMASMASMSMAMXXXMASAXAAASAAAAMSMMMAMMAAAASXSAMXSAXAAXMASMMAAAMSMSSXXSMSMMSASMMASXSAAMXMASAAMMSMSXSAMSXXASAXMASXMSMSMMASXMASAAMSSSMMXMXMASXM', 
        'XMMMAAMAMXAMXXSSMSASMSMSMSSSMXSAAMSAMXSMSMMMMMMMMXMSMMMAMASMMSAMXAMXAAAAMXMMMAMMSAXMSMXXSMMXSAAMAASMXMASAMMSXXMAXXAAASAMMSSXMSMAMAXXAMMMMMMA', 
        'XSXMSSMMSMMSSXAAAAXSAMAMXMXMAXSMMMSASAMAMMXAAAAAXAAMXSMXSAMXMAMAMASMSMSMSAXAMAMSMXMXXAMMXASMMXSSMMMSAMXMMMXMXMMXXASXXMMSAXAMXMMXMAMMAMAAAAMS', 
        'MMXMAMASAXSAMSMMXMSMMMAMMSMMSMMMXAXMMXMAMASXSSSSSMMXAXAMMXMMXXSXSSXAAXMASMSMSXSAAASMMASASAMXSAMXAAAXXXSMXMAMMSMSMMXSAMXSMMSAMXSSMSMXMASMSMSM', 
        'MXXSASMMAXMAMSXMMXMMXXASXMAAXAXXMSXXAXMAMMMAAAXAAMAMSMSMAAMMMXMXMXMXMSMMSXSXAXXMSMXASAMXXAXAMXSSSMMSMMXMAXMXAMXAAMAMXSAMAXAMAAAXAAMSSMXAXXSM', 
        'SAMMAMMMXMSMMMAXSASASXAXASMMSMMMMXAMXSSXSXMMMMMSMMASAAXMMXXAAAXXMASXMAMSMAMXMSMXMXSXMMSXSSMXSAMMXMAAXAAXSMSMASXSXMASAMASMMSSMSSMMMSAAXMAMASX', 
        'MASMMMXMAMAAAMMMSASAMXXSXMXAXAAAAMAMAAMAXMXMAXMXMMXSMSMSASXSSMXASASASXSMMAMAAAMAMAXMASAAAXAAXASAAMMSMSMMMAASXMAXXSMSXSAMXAXAAAMAXXMMSMMMMSMS', 
        'XAMMASASASXMMMSAMMMAMMMMMMMMMMSMXSAMXSMMMAASXSXAMSAMXXXMASAAAXSAMASAMXMMSMSMMSMSSSXSSMSMMSMMSSMMXXAAAXXAMSMMSMXMASAMMSAXMASMMMSSMXMAXAAASAMX', 
        'MSMSASXMASAASAMXSASXMXAAASAMMXMMMXAMAXASMMASAAMXMAAAASAMXMMMMMAMXXMMMMAAMXAMXXAMAMAXAAXMXXAXXMXMAMSSMMMSXXXAXMASXMASASXMAXXXAXAAMAMXMSMXSMXX', 
        'MAAMASAMSMXAMASMMXSASMSMMMASXAAAMSXMXMMMASXMMMASASMMXSXMMMSSXSASMSMAMMMSSSXSAMAMAMMMMMMMXSXMAXAXAAXAAAXXASMSMMXMAXXMMSXMSSSSSMXSSMSSMASAXMAX', 
        'MMMMXMASXAMXSAMASASAMAXMSSMMXMSMMAXSMSMMAMMAMXXMXMAMAXAMAMAAMXASAMXAXAMMAMMMMSXMSSXMASASMAXSMMMSMSSSSMSMXMAMAMSSSMMSAMAAAXAAAAAMAMAAXAMXAMMS', 
        'MSXSAMXAMAMXMMSAMMMAMAMAAAAAXXAMMMSMAAXMMMSAMMMMASAMXSMMSMMSMMMMAMAXSXSMAMASXMXSAAXSMSASMMMAAAAAAAAXMAAAMMAMAMMAMXXMASMMMSMSMMMSAMXSMSSMSAMX', 
        'ASAMMSXMAAAAXXMXSSSSMSSMSSMMSSMSSXAMSMSXAAMXMAASASASAAMAMSAAAAMSAMXAMXAMXSXSAMSMAMMSXMMMAXSMSMMSXMSXMSMSAMMSMMMXMMSSXMMSXAAAXAXXAMXAXAAAMMMM', 
        'AMXMAMAASMSMMSAMXAAAXAAXAMAAAAMAMSMMAAXMMMMSMMMMASAMXSXXSASMSSMMSMXASASXXSASMMAXAXAXXMXMMMSAMAXXAMXXXMMMMMMAMAMXAAASXAAMXMSMMASXSSMMMMSMMXAX', 
        'MMMXAXMMMAAMASASMMMMMSSMSSMMSSMAMMMSMMMMXSAAMSXMAMMMMMMMAXMXAMXAAMSMMAMMMSASMSXSAMMMXSAASAMXMXMSAMASMSASXMSMSXSSMMSSSMMSAMAMSMMMMAMXMXAAMSMS', 
        'XAASMXSAMSMMXSAMXXAAXXXAAMMAAAXXMAMMAAAAAMXMMAAMAXAAAAAMSMSXXMMXMAMAMAMAMMAMAMXMXAMAAMMSMASASXASXMASASASXMAAXAMMXMAMXMASMSXMAXAAXAMAXSMMMAAA', 
        'SMXSAAMMXXAXXMMMMXXAMMXMMSMMSSMXSAMXSMMMXXASXSXMXSSXSMXXAAXXSMSSSMSSMSSSMMAMAMXSASXMMMXXMXMAMMMMAMAMMMSMASMSMMMAAMXSXXXSXSXSMSXMSASAMXSAXXXM', 
        'XMAMMMMMSSMMMMAAASMSASMXSXMAXAAASXMAMXMASXMSAMXXXAAXMASXMSMAMAAAAAAAAXAMXXMSMAAXAMAMMSSMAMMSMMASXMASXMASAMMMMXAXXSMMMMMXAXAMXSAAMASXMAXMMMSX', 
        'XMASXMSAAAXSASMSXXAMAMAMSAMSSMMMSAMXSAMAMXXMAMASXMSMMAMAAMMXSAMSMMMMSMMMSMMXMMMSASXMAAAMASXMASMSXXMAXSAMXMAASMMSAXXAAASMMMXMAMMXMASAMXMSAAXM', 
        'MSASAAMMSMASASXXMMSMAMSMMAMAXAAAMAAMMMMSSMMXAMAXAAXAMAMMXMAAXAXXAXXSXAAAAMXXXAXMAMMMMXXSAMAXAMXSMMMAXMXMMSSXSAAMMMSXXMXAXASMMMMAMASMMAAMMXMM', 
        'XMASMMMMXAMXAMASXAAMXMXAXAMXSMMSSMMXXAAXAAASMMSSMMMSSMXXMMMMSSMSSMMAXMMSSSSMMSSMSMSSSMAMASMMMSAMAAXSAMMXAAMAMMMSAAMSMSSMXAXMSASAMXSMSMSXSAAA', 
        'MXMMXAXXXXXSAMXMMSSXSSSSMAMXMAAAXXSMSMSSSMMSXAXSMXAMAXXMAXAXXAMAAAMMSSMAAAASAXXAAAXAAMXMAAXAXMASMMSAAASMMSMMXMAMMXSAMMAMMSMASASXSAMAXAMASMSM', 
        'SAMXSXSMSMASXSXXMAMAAAAAXAMMSMMXSAXXXAAAAXAMMMMMMMMSAMXMSSSSXMMSSMMXAAXMMXMMSSMSMSMSMMXMMSSSMSMMAXAMMMSAMAAMXMXSAXSAMMAMXAAXMXMMMASMMAMXMAMA', 
        'MAXAMMMAAMAMXAMXMAXMMMMMSMSXASXAMMSAMXMSMMXSAMAXMXMMMXAAAAAAXXAXAXMMSSMXXAAXXXXMAXAAMAXXMMAXAAMMSSMXSXSXMSSMAMAAXXXAMSSMSAXMMXXASXSXMAMAMMMM', 
        'SSMASMXSMSMXSMAXMASMXSMXXAAMMMMMXAXMASMXAAASMXMSMMSAMMSSMMMXAXMSMMXXAXXAMSMMMXSMMMSMMXSAMXXMSMSAAAXSAMMXMAMMAMASMMSAMAXMAXXAXMXMMAXXMAXAXXMA', 
        'AASAMMAMXAMXAMAXMAMMAMASMXMSXAAXMASXMMXSMMXXAASAMASASAMAMMXSMAXAXMMSMSMSXXASXAMASAMXSMMMSMMAXAMMSMMXMAMAMAMSXSAXAAXAMXMSAXSSMAASMSMSXSSMSMSS', 
        'SAMXAMMXMMXAMXMSMXSMMMAXMMMXMXMXSSMAXMASXMAMSMSAMMSAMXXSMXAAXSSSMSAMXAAMAMAMAMSAMSMAAAAAAAMAMSMAAMAMXSSMSSXSAMASMMXSMXXMAXAAXSASAAASAXAMAAAA', 
        'XXXSMXSAMSSSXSSXXAAASMXSXAMAMSSMMASXMMASAMXXAMXAMAMAMXXXAMSSMMAXAMXSSMSMSMSMSXAXSAMXSMMMSXMSMMMMSSMSAMAMAMXMAMMAMXXXASXXMMSSMMAMMMMMXMASMSMM', 
        'SAMXSAMASAAMAMMAMSSMMXAMXMMXMAAASMMMMMASMMSSSSSMMXSXMXMMAMAAXMAMXSSMXXAAAXAAXMSXSXSAMASXMASAAXXMXAXMASXMMSSSSMXMAMMMAMXAAMXAMMAMXXMMXSAMMAXX', 
        'MAMAMXSMMXMMSMMSMAAAXXSXSMSMMSSMMXMASMAXAXAAXAAXSMMMSMASXMASMMMMMSAMMSMSMSMSMAXASMMMSAMAMXMMXMXASMMSAMXXAMMAMMAMAMMMXMSSMASAMSXMAAMAMXSAMXMX', 
        'SAMXSAMXAMXAAXXAMSMMSXMASAAAMMAAMXSSMMXSMMMSMSMMSAAAAAXAMXAMXMAAXMXMMAXAAAXAMMMAMASXMASXMMSAXMMMXAAMAXXMMSMAMMAXASAMXMAAXMMAAXAMSSMAMSXMXAXX', 
        'SXSAMMSMSSMSSSSMMXAXAAMMMSMSMSMMSAMASMAAAAXAAMMMSSMSSSMSSXAXAXXSSMSSSMXMSMMXSAMXMXMASAMAAAAMXSAXSMMSSXMASAMASMSSXMASAMSSMXSMMMXMAAXMMSAMXSAX', 
        'MMMXSASAMAAAMAAXASXASAMXMXXMAMXAMASAMMSMMMSMSMAMXAMAMAAMXMXSMSMMAMAAXMAMAMASMMMSXMXXMASXMSMXAAMMMMAAMXAXXMSMSAMAXXXAXMAXXAMAAAMMSMMXASAMAMMM', 
        'SAMXMASXXSMMMSMMXMMMMAMAASASXXMXSMMMSXMSMMAXAMAMSMMSSMMMAAMXAAAMAMMSMMMSAXMXAAAMAMSASXSXXXXSMMXAXMMSSXSMMMSAMXMASXMMMXMSMSSMMXXAMASMXSAMXSXA', 
        'SSSXSMMMMMAMAMSMAMAAAMSMSMAMXMAXXMAMSMAAXSMSSSMXAAAAAXSSMSAMXSSXSXMXXAXMMMXXXMMSAMSAMAMMXMASXXSASXAMXMMAMAMXMMMAMMAXSAMXXAAAAXSASAMXMSXMAMMX', 
        'MAXXXAASASXMASAXXSSSXXAMAMSMMMSMSSSMSMSMMXAAMAMSSSMSSMAAAMMXMXAAXSMAXXSASXXSASAMXMMMMAMMAMMMMXXMAXAXAASMMAXSMSMMSSMMSMXMXXXMMXAAMMMMMMAXMSSX', 
        'MSMMSSMSASXMXSAMMXMAXMXSAXAAXAAAXAXAMAAMMMMMSAMXXMMAMXXMMSXSMMMMMAMSSMSAMAASAMSAMXSASAMMASAXXXMXMAXSXXMXSMSSXAASXMXAXAAXSSXXSAMXMXSMASMSMAMX', 
        'XAAMAMAMXMXXXMAMXAXXSXMSXSSSMXXMMXMMMSMAAAXMMASMAXMASMXSAXXAAASASAMXAMMAMMMMXMMMAASMSAMSAXXSMXAXMAXSMSMXAMAMSMSMAMMXMXXXAAAXXMMMMAASASAAMAMM', 
        'SSXMAMXXMSMMMSXMSXMAMAXMMMMAMSSMMXAAAXMSSSXMXAAMSMMMSXAMAXXXMMXXSMMSAMMXMAXXMXASMMSAMAMMSMAMXASMMSSXAXMXMMAMMSXMAMMXSAMMSMMMXSXAMSXMMSXMSMSM', 
        'MASXMSMMMAAMAAAMXMASXMMSAMSSMAAAAXSMMSAXAXAXMMSAAAAASMXSAMMSMSXMMMASAMASMMMASXXSAAMXMASAXMSMAMMAXMMMSMMAMMMSMAXSAAMAMASAXASXAMMSMMASAMAXAAAM', 
        'SAMXAAAASMSMSSXMAXAXAMXSAXAAMSSMMMAAXMMMAMMSAMXMSSMMSAAMASAAAAXAXMASAMASAAXSXMASXMASMAMMSAAMMMSSMAASAASMSAAAMMMSSSXASAMXSAXMASAMXMASAMMSMSMS', 
        'MXSMSMSMSMMAMXMSXMMSMMXSXMSSMXAMXXSXMSAMXMASXSXMXAMXMMMSAMXMAMASAMXSAMSSMMMXAMAMMXXMASXAMMMSXXXASXSSXXXMAMSXSXXMAMMASMMXMAMSMXMAMXMSAMXXXXAX'] 

print(question4(test2))